# =============================================================================
# Файл конфигурации для создания окружения Conda
# проекта "Программный бот для отслеживания аномалий котировок криптовалют"
#
# Для создания окружения выполните в терминале команду:
# conda env create -f environment.yml
#
# Для активации окружения:
# conda activate crypto-anomaly-bot
# =============================================================================

name: crypto-anomaly-bot

channels:
  - conda-forge
  - defaults

dependencies:
  # Основной язык программирования
  - python=3.10

  # Библиотеки для анализа данных
  - numpy
  - pandas
  - matplotlib

  # Библиотеки для взаимодействия с API и GUI
  - tk              # GUI-фреймворк Tkinter для графического интерфейса
  - pip
  - pip:            # В состав conda, к сожалению, не входит ccxt
    - ccxt==4.3.42    # Библиотека для взаимодействия с API криптобирж
